# Creation of Service Account

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chief-admin
  namespace: default

---
# Creation of Cluster Role

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
# Creating a cluster binding role that binds together the service account and the cluster role

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chiefadmin-monitor
subjects:
  - kind: ServiceAccount
    name: chief-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: monitor
  apiGroup: rbac.authorization.k8s.io
